CREATE TABLE comment
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version   INTEGER,
    content   VARCHAR(255),
    uuid      UUID,
    author_id BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE post
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version   INTEGER,
    title     VARCHAR(255),
    content   VARCHAR(255),
    uuid      UUID,
    author_id BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version  INTEGER,
    username VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT uc_comment_uuid UNIQUE (uuid);

ALTER TABLE post
    ADD CONSTRAINT uc_post_uuid UNIQUE (uuid);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES "user" (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES "user" (id);